#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "143.248.188.193";
$SERVER_PORT = 8091;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
